<?php

/**
 * 定向问答
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class DefaultController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation apiBangbangGet
     *
     * 定向问答.
     *
     *
     * @return Http response
     */
    public function apiBangbangGet()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $a = $input['a'];

        $b = $input['b'];

        $c = $input['c'];


        return response('How about implementing apiBangbangGet as a get method ?');
    }
}
